#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

require('dotenv').config();
const cwd = process.cwd();

function getCli() {

  const project = process.argv[3] ?? 'api';

  const cliPath = path.join(cwd, `dist/apps/${project}/cli.js`);
  if (fs.existsSync(cliPath)) {
    return require(cliPath);
  }
  console.log(`project ${project} does not exists`);
  return null;
}

const cli = getCli();

if (cli) {
  return cli;
}

console.log('No dist folder found. Building...');
execSync('nx run-many -t build', { cwd, stdio: 'inherit' });
console.log('Build complete.');
console.log('Try running again.');
console.log('Remember that every time you make a change in the api, you must run npx nx build api');

